### ISSUE TITLE
Destroyself + RedirectID

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1014]
### Describe the bug

These two currently don't work together. The helper that calls it will destroy itself instead of the redirected target.

### To Reproduce

1. Download this debug version of KFM
[kfmdestroyself.zip](https://github.com/ikemen-engine/Ikemen-GO/files/10892425/kfmdestroyself.zip)

2. Create helpers with P2
3. KFM's helper will destroy itself instead of the enemy helpers, despite using RedirectID

### Expected behavior

Destroyself with RedirectID should destroy the targeted helper, of course. Incidentally, the state controller _might_ need to be adjusted to that the rest of the state is still processed if it uses RedirectID, like what happened with ChangeState and SelfState.

### Engine Version (or source code date)

28/02/2023

### Operating system

Windows

**Comment by K4thos** [comment]
I couldn't reproduce it. I assume you've experienced this problem because of typo - in your test kfm you've used "reidrectID" instead of "redirectID".

But there was a different problem here that has been fixed: when destroyself was used it stopped further script execution even if it was redirected to different id

**Comment by potsmugen** [comment]
Silly me. I was going trough my list of things to report, so I'm sure it didn't work at some point, but then made that typo in the test case. Well what matters is that it's working and something good still came out of this report. Thanks.
