### ISSUE TITLE
Supermystery's Sonic: Cloning Bug - v0.99.0-rc.1

### ISSUE THREAD

**Issue by jrm1007** [ikemen-engine/Ikemen-GO#1027]
### Describe the bug

In v0.99.0-rc.1, Characters made by Supermystery (specifically Sonic characters) are bugged, and end up creating clones when they collide with each other. Both the clone, and the Character are controllable, but only one dies when F1'ed.

(This behavior does not occur in 0.98.2)

### To Reproduce

1 - Download Supermystery's Sonic from MUGEN Free For All / Database
2 - Have Sonic move, or Spindash, and make the opponent hurt him

### Expected behavior

They are only meant to collide with each other, without the creation of clones, this behavior does not occur in 0.98.2

### Screenshots / Video

(0.98.2)
https://user-images.githubusercontent.com/78282477/224160379-59169749-f57a-4b15-8dc0-0d8601df8ad4.mp4

(0.99.0-rc.1)
https://user-images.githubusercontent.com/78282477/224161349-a85834c8-89bd-4152-9515-fc17865319b4.mp4

### Engine Version (or source code date)

v0.99.0-rc.1

### Operating system

Windows

**Comment by potsmugen** [comment]
This bug is pretty interesting. Some observations:

- The bug is caused by helper 870
- It only happens if the player that is hit is holdind any direction
- It is fixed if you remove keyctrl from that helper, or if you make its parent create it one frame later
- If the right conditions are met, the 870 helper has ctrl in the very first frame where it is created, and can thus exit its own state and enter the root states, thus creating a clone

Here's a debug screenshot where the bug is about to happen:

![ikemen004](https://user-images.githubusercontent.com/107247004/224164781-141d6d75-f230-4c44-9e30-7bdc75879c17.png)

Notice that ctrl = 1, time = -1, and the anim and sprite data is missing. This combined with having keyctrl allows the helper to enter the hardcoded states (walking, crouching and jumping) with the respective input.

If the helper is created one frame later, it will not enter this "limbo" state and will act normally, without causing any bugs.

[Also here's a more convenient link to the character.](https://mega.nz/file/YQwz1YJK#Vky53xHIeybVd-GTjrfC2849RSsZJtaOVJFsi9cLytU)

**Comment by Shadic13** [comment]
The clone also happens to me when playing with OHMBY's characters when I face against an AI out of nowhere a clone of my character appears.
