### ISSUE TITLE
Muffet Half-Baked Hyper issue

### ISSUE THREAD

**Issue by waspennator** [ikemen-engine/Ikemen-GO#1200]
### Describe the bug

From what i've been testing, this hyper seems to work alright on Ikemen GO, but it seems to have one notable issue that pops up if the first hit that activates the hyper ends up KO'ing the opponent. When the oven explodes, the opponent will drop out of the sky back onto the stage (Only supposed to happen if the hyper doesn't KO the opponent), but Muffet will still go through her extra animation that only plays if the hyper KO's her opponent.

The hyper itself plays out fine on GO if the opponent gets drained to 0 HP later during the hyper, problems only seem to occur if it's the first hit that KO's the opponent.

### To Reproduce

1: Download Muffet 
[Muffet.zip](https://github.com/ikemen-engine/Ikemen-GO/files/11331526/Muffet.zip)
2: Start a match against anyone (I used KFM) and use F2 to drain the opponents HP to 1.
3: Perform her Half Baked Hyper (Down, Down X+Y) and make sure the first hit KO's the opponent.
4: Watch as the opponent drops out of the sky after the oven explodes.

### Expected behavior

The opponent shouldn't drop back onto the field after the oven explodes if the first hit KO's them.

### Screenshots / Video

[Muffet Ikemen GO.zip](https://github.com/ikemen-engine/Ikemen-GO/files/11331776/Muffet.Ikemen.GO.zip)
[Muffet Mugen.zip](https://github.com/ikemen-engine/Ikemen-GO/files/11331783/Muffet.Mugen.zip)

### Engine Version (or source code date)

Nightly Build 4/25/23

### Operating system

Windows

**Comment by potsmugen** [comment]
This is a small difference in how LifeAdd works. In Mugen, using the "kill = 0" parameter makes the character's life *never* go below 1, even if it was already 0. In Ikemen if life was already 0 using kill = 0 won't change that, which makes more sense.

This is such a specific scenario that I'm not sure it's an issue. Maybe that behavior could be replicated if the char is not "Ikemenversion".

In the meantime, if you want to adapt the character just change the "trigger1 = life = 1" with "trigger1 = alive = 0".

**Comment by potsmugen** [comment]
I was reworking the code to do that healing 1 point thing I mentioned, but in doing that I noticed another issue: Mugen allows life to be changed during roundstate 3 (or any point), while Ikemen does not. This is also needed for that move to work as in Mugen. However, Ikemen's way is flat out better because it ensures you can't heal yourself after the round ends and win by time over.

For those reasons I think this quirk is not worth implementing.

EDIT: Actually, after studying Mugen further I think it _is_ worth implementing. It's tied to another feature we haven't implemented yet.
