### ISSUE TITLE
Source code download for v0.99.0-rc.1 is empty

### ISSUE THREAD

**Issue by root2185** [ikemen-engine/Ikemen-GO#1260]
### Describe the bug

Source code download is empty.

### To Reproduce

1. Download the source code https://github.com/ikemen-engine/Ikemen-GO/releases/tag/v0.99.0-rc.1.
2. Both versions are empty.

### Expected behavior

Archives not empty.

### Engine Version (or source code date)

v0.99.0-rc.1

### Operating system

Linux

**Comment by root2185** [comment]
This is normal so. 
No source code.

**Comment by K4thos** [comment]
no, it means that at the time of release the configuration didn't add a source package. And since then the configuration has been changed, so the report is no longer relevant . We won't go back in time to make the release again and you have a commit hash anyway that you can use to get the source files from that exact date

**Comment by K4thos** [comment]
it is useful, indeed. It should work fine now, but I will double check it for the next release to be sure that it's there, thanks for the report.
