### ISSUE TITLE
Some moves are muting/freezing Ikemen.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#1325]
### Describe the bug

Performing certain moves can mute/freeze Ikemen. This is the first time I've every experienced anything like this.

### To Reproduce

Download the characters [chars.zip](https://github.com/ikemen-engine/Ikemen-GO/files/12078717/chars.zip)

Perform Ryuhaku's qfcx2+punch super(it has to hit) for the game to mute and moments later freeze.
Perform Fei Long's qcbx2+kick super for the game to instantly freeze.

### Expected behavior

To not freeze.

Works just fine on 98.2 and previous versions.

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/77592586/b7fb07f1-d3c1-4c32-8e45-23adcd3010fd

https://github.com/ikemen-engine/Ikemen-GO/assets/77592586/e299326e-aff5-4060-bace-829f8b7a7d10

### Engine Version (or source code date)

v0.99.0 rc1 and Nightly

### Operating system

Windows

### Extra context or search terms

The program doesn't recover from freezing, I have to force it's shutdown.

**Comment by Finally1994** [comment]
I tested it with Ryuhaku
It seems that the hit sound [1,4] is the culprit. It seems to freeze when this is played, and there is no problem if you replace it with another sound.

**Comment by UrsoManso** [comment]
> I tested it with Ryuhaku It seems that the hit sound [1,4] is the culprit. 0.99 seems to freeze when playing this. FeiLong is [10,14]

Could it have something to do with the audio engine rework?

**Comment by UrsoManso** [comment]
But it works on MUGEN and it used to work on previous builds.

**Comment by ZyonZZ** [comment]
> But it works on MUGEN and it used to work on previous builds. I feel like the audio engine rework did more harm than good.

I have more than 500 chars.. and honestly, this error has not happened to me in any of them..
Are these characters from the same author?
Could it be that he is using a sound frequency that Ikemen is not compatible with?
The subject is interesting.. in any case.. if you can fix that sound and there are too few characters that have it, you could fix it..

And if you know the reason for the crash... either as I told you... the frequency of the sound... it could be increased just to avoid these problems...
but it is necessary to find the true reason of the error..



The only problem regarding audio that I have experienced is:
that sometimes the stereo volume is lowered depending on the location of where you are on stage... (far to the left... only the left horn sounds... far to the right... only the right) is strange because in no """popular fighting game""" there is an effect like that... besides being stereo... the sound is hollow on one side... but that's another story xD

but ensuring that it is a regression is somewhat extreme... in previous versions the audio was bugged when configuring it in Options... something that has been fixed...
In truth, this version if I consider that it improves the audio to the previous one..
Except for the error you mentioned.

**Comment by Lazin3ss** [comment]
@UrsoManso being knowledgable on Ikemen GO's codebase, getting rid of OpenAL was really the way to go. Now, we only have to fix all these regressions and discrepancies. Don't undervalue Sam's work, please.

> The only problem regarding audio that I have experienced is:
that sometimes the stereo volume is lowered depending on the location of where you are on stage... (far to the left... only the left horn sounds... far to the right... only the right) is strange because in no """popular fighting game""" there is an effect like that... besides being stereo... the sound is hollow on one side... but that's another story xD

Set "PanningRange" to 0 in config.json.

**Comment by UrsoManso** [comment]
> @UrsoManso being knowledgable on Ikemen GO's codebase, getting rid of OpenAL was really the way to go. Now, we only have to fix all these regressions and discrepancies. Don't undervalue Sam's work, please.

I'm obviously uneducated on the subject so I'm basically talking from my own perspective because I didn't used to have issues like this one or sound effect volume being affected by other sound effects and everything else remains the same. It wasn't my intention to discredited anyone's work.

**Comment by Finally1994** [comment]
This freeze also occurs with BGM (.MP3)
Characters created in the old days may be because they made an effort to reduce the file size according to the performance of the PC at that time.

**Comment by K4thos** [comment]
I assume it's the same problem as #1286
