### ISSUE TITLE
Camera position problem on some stages in HD resolution

### ISSUE THREAD

**Issue by Kiwi1444** [ikemen-engine/Ikemen-GO#1545]
### Describe the bug

Camera is too high on some stages in HD (in my case 1280x720) res. Lake of fire stage for example: 
**_Mugen 1.1_**
![Mugen1 1](https://github.com/ikemen-engine/Ikemen-GO/assets/56668390/9646240c-0360-4d51-8d79-6d3d5a289323)
_**IkemenGo (1280x720)**_
![IkemenGo720p](https://github.com/ikemen-engine/Ikemen-GO/assets/56668390/47893425-5591-4835-8030-39f21591494f)

Problem doesn't persists on low resolutions:
_**320x240**_
![IkemenGo320x240](https://github.com/ikemen-engine/Ikemen-GO/assets/56668390/81162646-842d-478b-afd4-858e3463bd80)
_**640x480**_
![IkemenGo640x480](https://github.com/ikemen-engine/Ikemen-GO/assets/56668390/e2650204-1ec4-4d40-b202-88e1c41649f5)
_**960x720**_
![IkemenGo960x720](https://github.com/ikemen-engine/Ikemen-GO/assets/56668390/f94fee88-9327-43f2-8a56-552d0e40b489)

### To Reproduce

1. Download and install Area of fire stage (for example from [Mugenarchive](https://mugenarchive.com/forums/downloads.php?do=file&id=157046-area-of-fire-drolldiamond))
2. Run IkemenGo
3. Set resolution 1280x720
4. Run match on that stage

### Engine Version (or source code date)

v0.99

### Operating system

Windows

### Extra context or search terms

The same problem on [Frost's grave ](https://mugenarchive.com/forums/downloads.php?do=file&id=69224-frost-s-grave-1-1-thexd3ath-xwagnerplaguesx), [Cherry Blossom Bridgewater](https://mugenarchive.com/forums/downloads.php?do=file&id=179814-cherry-blossom-bridgewater-daniel-alanis), [City destroyed ](https://mugenarchive.com/forums/downloads.php?do=file&id=164855-city-destroyed-1-0-update-drolldiamond-fix-el-sr-x), [Art Gallery](https://mugenarchive.com/forums/downloads.php?do=file&id=170458-art-gallery-antares-) stages. On the stage [Sky Battle - Night 1.1](https://mugenarchive.com/forums/downloads.php?do=file&id=71102-sky-battle-night-1-1-ziltama) camera OK, but floor position is wrong in IkemenGo:
![2023-12-04 20_05_49](https://github.com/ikemen-engine/Ikemen-GO/assets/56668390/f5a494a8-998e-43e2-8a25-63a21975c0b4)
Compared to Mugen:
![2023-12-04 20_06_11](https://github.com/ikemen-engine/Ikemen-GO/assets/56668390/1e06f2a3-181a-4877-a0fb-8305fa540488)

**Comment by K4thos** [comment]
The floor's y-position appears to be fixed in the latest nightly build, most likely due to #1633.Note that the difference in Mugen 1.1, which by default displays a 4:3 image with black bars, is due to a missing feature. Currently, Ikemen does not support the StageFit = 1 setting, which has already been reported in #170. Therefore, I'm closing this issue.

Screens from latest nightly using 720p res:
![ikemen007](https://github.com/ikemen-engine/Ikemen-GO/assets/8928195/e304dfb6-e7cc-4a69-b533-03f3710b5d56)
![ikemen008](https://github.com/ikemen-engine/Ikemen-GO/assets/8928195/e40dcaaa-bf6a-4a7c-bb7e-63aeaa06b8ae)
