### ISSUE TITLE
Character victory music plays at wrong time

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1632]
### Describe the bug

The character victory music plays at a wrong time when compared to the default screenpack victory music.

(Marginally related but I think victory music could be defined in the def file)

### To Reproduce

1. Add victory music to the screenpack
2. Check timing
3. Add specific victory music to Kung Fu Man
4. Compare the timing

### Expected behavior

Specific music should start at the same time as the win quote screen, like the screenpack music.

### Screenshots / Video

Screenpack music:

https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/c64b130f-6d9a-4dcd-bcb3-7ed47caf1fbe

Character music (from select.def):

https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/182e6c09-f8ae-4546-90cb-b26d6481815e

### Engine Version (or source code date)

10/02/2024

### Operating system

Windows

**Comment by K4thos** [comment]
This was actually intentional. It fulfilled a feature request to implement this type of victory music: https://www.youtube.com/watch?v=vIrfCs_O47Q&t=42s. Perhaps it should be renamed to "win screen" instead of "victory music" to avoid confusion. Or maybe even removed altogether during the Lua rewriting to prevent feature bloat. I believe that the functionality of screenpack should not be expanded upon by default much beyond what Mugen offered, but rather, it should be managed through external expansions. Something like this could be implemented either through an external module or a common state, thanks to the bgm sctrl.
