### ISSUE TITLE
Black Heart Characters: Effects Work Improperly

### ISSUE THREAD

**Issue by CyborgSun** [ikemen-engine/Ikemen-GO#1767]
### Describe the bug

With the latest versions of all "The Black Heart" characters (from PoTS' website) in the latest nightly builds, most effects are stuck in the center of the stage. The effects work properly in older IKEMEN builds. A simple screenshot example is shown.

### To Reproduce

1. Use the latest nightly build
2. Download any Black Heart character from PoTS website (Janos is one of the most immediately obvious though, due to his constant shadow effect)
3. Install them and see for yourself in any mode

### Expected behavior

These effects shouldn't snap to the center of the stage, and should be emitting from the actual characters (be they the victim or the attacker).

### Screenshots / Video

![center blood](https://github.com/ikemen-engine/Ikemen-GO/assets/151224011/7a71ec69-a46a-43dc-8f1b-0f6aaab0cdc7)

### Engine Version (or source code date)

Nightly Build (2024-04-24 used in screenshot)

### Operating system

Windows

**Comment by K4thos** [comment]
It's caused by the presence of ikemenversion = 0.82 (ignored by mugen) in the def file, alongside mugenversion = 1.0. Probably inteded. @potsmugen?

**Comment by potsmugen** [comment]
That sounds about right. Ikemenversion forces Mugen version 1.1 internally so the explods are defaulting to that behavior. Borghi asked me if I could fix things like these so I can fix it in the chars themselves later.

Edit: You can just comment out the ikemenversion lines in the def files. The chars don't actually use Ikemen coding features since the game was originally made for Mugen. I'll update the archives accordingly.

If another case like this happens we can make Ikemenversion only affect Mugenversion after a certain version number.

**Comment by CyborgSun** [comment]
Excellent, that was exactly the issue, removing the line makes them work right again.

![it works yay](https://github.com/ikemen-engine/Ikemen-GO/assets/151224011/27fb0920-0ae7-4e57-8036-213c4a19395b)
