### ISSUE TITLE
Damage overflow works different from mugen 1.1

### ISSUE THREAD

**Issue by RealFoobs** [ikemen-engine/Ikemen-GO#1829]
### Describe the bug

The meme character "F1" isn't working as intended.

### To Reproduce

1. Download F1 [here.](https://hsiehtm.tripod.com/mugen/chars.html)
2. Make it fight any character.
3. F1's projectiles will malfunction and p2 will be stuck looping into state 5000 instead of dying.

### Expected behavior

F1 can kill any conventional character on mugen 1.1. It looks like the damage overflows in that engine as well, but eventually the target is killed.

### Engine Version (or source code date)

Nightly (2024-06-06)

### Operating system

Windows

### Extra context or search terms

```[State 1000, 5]
type = Projectile
triggerall = P2Life != 0
trigger1 = P2Name != "Psycho Shredder[S]"
trigger2 = Time > 100
projanim = 1000
projremovetime = 1
id = 1
attr = C,NA
damage    = 1000000,1000000
numhits = 0
givepower = -1000000
guardflag = A
pausetime = 0,0
sparkno = -1```

The stupidly high damage along with the character's attack constant being 10,000,000 causes damage to overflow,

**Comment by potsmugen** [comment]
Sure enough, setting KFM's attack and light punch damage to 1000000 also makes that attack not kill. But something's weird. For some reason damage is being set to 0 instead of overflowing.

EDIT: Oh. It's set to 0 because it can't heal more than the life that's missing from the char. Mugen doesn't seem to do this type of clamping. But the issue is not specifically that.
