### ISSUE TITLE
The "poop" sound issue

### ISSUE THREAD

**Issue by shin258** [ikemen-engine/Ikemen-GO#1956]
### Describe the bug

The majority of gen 1999 to 2005 mugen era have a sound (popping) with low frequency sample, exclusively with ikemenGO 0.99/dev.

### To Reproduce

download a gen char in 1999 to 2005 with 11,025khz 8bit to 22khz 16bit and you get this in video section.

### Expected behavior

To get same or similar thing to winmugen plus.

### Screenshots / Video

Save as the video (due of hevc format)

in winmugen plus:
https://github.com/user-attachments/assets/c6512a54-933b-4304-9e14-00bf9c5f55b7

in Ikemen GO build (v.0.99 and 07-08-2024 and after):
https://github.com/user-attachments/assets/7b219557-a01d-4cef-9780-e689d946b958

### Engine Version (or source code date)

v0.99 and dev.2024-08-15

### Operating system

Windows

### Extra context or search terms

Sound

**Comment by SuperFromND** [comment]
Thought this might be related to us recently updating beep (our sound library), but this affects 0.99 too? Odd.

**Comment by shin258** [comment]
> Thought this might be related to us recently updating beep (our sound library), but this affects 0.99 too? Odd.

Hi Super i'confirm i have this since i have discover ikemengo with the 0.99 and are here since to the last dev build actualy.

I have not this sound problem in winmugen plus of course and also no problem too on mugen 1.1b4 (same sound as winmugen plus).

**Comment by ghost** [comment]
yep I get this too on latest.....pop everytime a sound starts for certain chars with those paremeters for sound

**Comment by Jesuszilla** [comment]
Seems to be caused by extra data in the .SND? If I export the WAV and re-import it and re-save the .SND in Fighter Factory Studio, the pop disappears. Attached is the diff of the two .SND files for sound 20,0.
![image](https://github.com/user-attachments/assets/8066b932-7fa8-4260-a514-9c63119e0fcf)

I extracted the sound as-is from the .SND using a hex editor and played it back in Beep's speedyplayer demo and heard the pop (attached it in the Discord). It must be an issue with how beep is processing the WAV.

**Comment by MarkKremer** [comment]
Thank you for the side-by-side @Jesuszilla! This made tracking down the problem really easy. I've created a PR for Beep with a fix.
