### ISSUE TITLE
No suction in air combo

### ISSUE THREAD

**Issue by netyzh** [ikemen-engine/Ikemen-GO#2008]
### Describe the bug

When in air combo,Uma's Akiko lose suction when use 426a
It behaves normal in mugen or not in combo.

426a's stateno is 1300 and it creates a helper(stateno 1330) for playerpush.

### To Reproduce

Download character from https://onedrive.live.com/?cid=DD9E6829B1DE854C&id=DD9E6829B1DE854C%21161&parId=DD9E6829B1DE854C%21160&o=OneUp
Use 426a twice.

### Screenshots / Video

In IkemenGo:

https://github.com/user-attachments/assets/44471e76-5c6e-4226-8572-960bfa894546

In Mugen

https://github.com/user-attachments/assets/78cd28af-0267-4896-bd1e-2cc52e5a4419

### Engine Version (or source code date)

nightly build(20240916)

### Operating system

Windows

**Comment by potsmugen** [comment]
It's caused by this block:

```
[state 1360]
type = width
trigger1 = 1
value = -100,-100
```

Hard to explain but in Mugen this results in a wide "pushbox" because Mugen automatically adjusts it so that the smallest value is always to the back. In Ikemen it shifts the pushbox behind the char but in an unintended way.

Will have a fix in my next PR.

Edit: On a closer look it looks like Mugen does that correction for some parts of the pushing code but not others, which seems a little buggy. I'm not sure if we should reproduce it completely.
