### ISSUE TITLE
Stage reflections and shadows problem

### ISSUE THREAD

**Issue by Kiwi1444** [ikemen-engine/Ikemen-GO#2150]
### Describe the bug

On the stage Amitaku Outskirts by Strong FS reflections has wrong scale and shadows looks less transparent.

### To Reproduce

1. Download and install Amitaku Outskirts stage (you should choose Amitaku_Outskirts(1280x720).def)
2. Start the match
[Amitaku_Outskirts_MUGEN_1_.zip](https://github.com/user-attachments/files/17937956/Amitaku_Outskirts_MUGEN_1_.zip)

### Expected behavior

Like in Mugen 1.1

### Screenshots / Video

Mugen 1.1:
![2024-11-28 00_01_47](https://github.com/user-attachments/assets/6b90888d-c070-447a-9d70-f201ca712985)

Ikemen Go: 
![2024-11-28 00_02_10](https://github.com/user-attachments/assets/acebebd2-b92d-4737-a968-0b045d62cc8f)

### Engine Version (or source code date)

Nigtly 2024-11-27

### Operating system

Windows

**Comment by potsmugen** [comment]
We might have the wrong default values for the shadows since the stage has the [Shadow] group commented out.

As for the reflection the author left a scale under the [Reflection] group, even though that parameter didn't exist at all in Mugen. I'm not sure we should lock that feature behind ikemenversion just because of bad syntax.

Update: Yeah. We default to 128,128,128 instead of 0,0,0.
