### ISSUE TITLE
Joystick not working on Linux.

### ISSUE THREAD

**Issue by YoshinobuTheFox** [ikemen-engine/Ikemen-GO#2207]
https://github.com/user-attachments/assets/b38d2a45-ea70-4453-a8fb-43b8bde0dd5e

**Comment by Jesuszilla** [comment]
Run I.K.E.M.E.N-Go from the command line and then try to config it. Is there any output to the terminal?

**Comment by YoshinobuTheFox** [comment]
> Run I.K.E.M.E.N-Go from the command line and then try to config it. Is there any output to the terminal?

I'm not running IKEMEN GO from the command.

**Comment by Jesuszilla** [comment]
I didn't say you were, I'm asking you to please do it _now_ so we can see if there's any output.

EDIT: Can confirm 360/Xinput controllers are not working properly on Linux as of the config.ini changes. I can't get my Atari gamepads in 360 mode to register any button presses when porting over my config.json to config.ini. It should just work.

EDIT2: Apparently if you're editing the config.ini directly, the mappings written by the defaultConfig.ini do not match what the engine actually writes when going through joystick config manually (the latter was tested with a RetroBit Genesis/MD controller and an 8BitDo SN30 Pro on macOS):

What the defaultConfig.ini thinks is being written:
```ini
[Joystick.P1]
Joystick = 0
Up       = 10
Down     = 12
Left     = 13
Right    = 11
A        = 0
B        = 1
C        = 5
X        = 2
Y        = 3
Z        = -12
Start    = 7
D        = 4
W        = -10
Menu     = 6
GUID     = 

[Joystick.P2]
Joystick = 1
Up       = 10
Down     = 12
Left     = 13
Right    = 11
A        = 0
B        = 1
C        = 5
X        = 2
Y        = 3
Z        = -12
Start    = 7
D        = 4
W        = -10
Menu     = 6
GUID     = 
```

The format that is actually being written (and read by the engine; note how P1.Joystick is oddly missing):
```ini
[Joystick]
P1.GUID     = 030000000d0f0000c100000072050000
P1.Up       = 18
P1.Down     = 21
P1.Left     = 19
P1.Right    = 20
P1.X        = 3
P1.A        = 2
P1.B        = 1
P1.Start    = 9
P1.C        = 7
P1.Y        = 0
P1.Menu     = 8
P1.Z        = 6
P1.D        = 4
P1.W        = 5
P2.Right    = 12
P2.Up       = 11
P2.Left     = 14
P2.Down     = 13
P2.A        = 0
P2.B        = 1
P2.Z        = 5
P2.C        = -12
P2.X        = 2
P2.Y        = 3
P2.Start    = 7
P2.D        = 4
P2.W        = -6
P2.Menu     = 6
P2.Joystick = 1
P2.GUID     = 030000005e040000e002000003090000
```

If I edit my Linux config.ini to match that format (GUID Is not necessary for Linux or Windows FYI), it works. So the default config.ini might not have proper mappings the first go-around? I believe the controller defaults are for an XInput device out of the box, at least on Windows. The bindings may be different for other OSes and that may be why we (Linux and macOS users) have to reconfigure them? I know every time I get a fresh copy of IKEMEN-Go, up/down are swapped on the D-Pad on Linux for my Atari Gamepads in XInput mode. Because GLFW has no bindings for this particular gamepad of mine, it technically can't go through normal joystick setup (no name comes up so it's not properly recognized as an XInput controller and thus can't set up the proper exceptions for the "stuck" triggers to go through setup).

Think we should provide different defaults for the different platforms if that's the case? I'd aim for XInput layout, SF4 style (Z on RS, C on RT, D on LS and W on LT). That should support the majority of user preferences.

**Comment by YoshinobuTheFox** [comment]
And by the way... I'm using the Nightly version.
