### ISSUE TITLE
Hyper DBZ Character issues

### ISSUE THREAD

**Issue by RollinJay** [ikemen-engine/Ikemen-GO#230]
Buu's  Pain Train ( Lvl 1 236236 k) doesn't function correctly

Gotenks  Super Saiyan 2  (Lvl 2 22 mp+mk) layering issues. Hes behind the background. This also occurs in Super Gokus Whis crystal ball outro, and Babidis crystal ball super

Using legacy continue screen still reads from system.def instead of reading from fight.def like legacy mugen does.

https://drive.google.com/folderview?id=1jqk3cU2rAE2AMQfXHOAnQtUfI1RgJTJy

Link to the build in google drive so u can check individual files

**Comment by Orochikyocr** [comment]
Recently we found zoom sctrl mess with other stuff present in the same statedef, any of these movements you are reporting is using zoom?

**Comment by RollinJay** [comment]
the game is a port from mugen 1.0 so no zoom is used

**Comment by RollinJay** [comment]
Buu example
https://streamable.com/dnypaa

Gotenks Example
https://streamable.com/eakstm

**Comment by Orochikyocr** [comment]
I found some clues to what is happening.
In the case of Bu, there is no changestate o targetstate in the opponent state 2511. It is unbeknownst to me if Mugen has some hard coded code to send chars to a common hitstate. 
I added this as a workaround  
`[State 0, SelfState]
type = SelfState
trigger1 = enemynear,NumHelper(2510)
value = 5102
ctrl = 0
ignorehitpause = 1
persistent = 1`

With Gotenks is superpause messing with two explods 2701 and 2702, nulling superpause or the explods is a good workaround.

The Farmer bonus not dying is Lifeadd not working properly, the SCTRL is located inside a helper. I had troubles with lifeadd before, I always use lifeset, because lifeadd is working odd sometimes.
Also, the Farmer tank having a lot of health is because there is a defencemulset that for whatever reason It does not work on Mugen.

`[State -2, move]
type = varset
trigger1 = 1
var(31) = 999999999999

[State -2, move]
type = defencemulset
trigger1 = 1
value = var(31)`

**Comment by Orochikyocr** [comment]
Sorry for the quick post.
I found why lifeadd works odd sometimes, Lifeadd is affected by defencemulset, something that does not happen in MUGEN.
IMO the right behavior is the one in Ikemen GO, because this solves defencemulset NOT affecting grabs in Mugen.

**Comment by K4thos** [comment]
both problems are no longer reproducible on latest github build, so I'm assuming they are already fixed.
