### ISSUE TITLE
PALFX ISSUES

### ISSUE THREAD

**Issue by JeanneSoul** [ikemen-engine/Ikemen-GO#288]
there is some palfx not working correctly when chars played at mugen and define palfx as black color it would be black but when chars add on IKEMEN the colors turn into white,, maybe that would be issues about RGB algorithm for Palfx

**Comment by K4thos** [comment]
please, always provide links to problematic content and repro steps what has to be done for the issue to show up in game. Report like this is not enough to reproduce problem locally (we're not gonna test all kinds of palfx settings blindly to get the result you've mentioned)

**Comment by JeanneSoul** [comment]
uhh Okayy my bad... here is the code... in my opinion maybe its because "InvertAll" Contoller did'nt works or something missing logic with RGB color

[State 0,PalFXWiz]
type=PalFX
TriggerALL=1
trigger1=IsHelper(011)
trigger2=IsHelper(012)
trigger3=IsHelper(013)
Time=99999
add=0,0,0
mul=256,256,256
color=0
InvertAll=1

its should be become black color in Mugen but when its Run by Ikemen Go it become white color which mean color not inverted

"SS from Mugen 1.1 Engine OpenGL"
![palfxBugMugen](https://user-images.githubusercontent.com/86551597/124555223-09a60000-de61-11eb-8377-1046cfae9cd9.png)

"This SS from IKEMEN engine" 
![palfxBugIkemen](https://user-images.githubusercontent.com/86551597/124555311-28a49200-de61-11eb-9747-1d7eceff6eb6.png)

**Comment by JeanneSoul** [comment]
Link chars "just in case needed "
https://bit.ly/3c8isSZ

**Comment by K4thos** [comment]
tested this character in mugen 1.0 (after changing mugenversion and removing zoom parameters to be able to load it) and the result in that engine is exactly the same as ikemen go:
https://user-images.githubusercontent.com/8928195/125634822-6f231f17-9aea-42ce-a477-f4d7a99aad29.mp4
From this I assume it's very likely that it's mugen 1.1 being bugged, not the other way around.

**Comment by K4thos** [comment]
reposting result of PlasmoidThuder's investigation regading 1.0/1.1 engine differences:

> The code is a mess but I think I get what's going on.
There is no bug.
1.1 added the ownpal parameter to Explods.
Explods with ownpal use their own palette, meaning PalFX sctrls in the state would have no effect on them.
1.0 obviously didn't have this, so Explods would be affected by PalFX.
You can tell because the PalFX isn't actually doing anything to the fire/explosion effect in 1.1.

**Comment by K4thos** [comment]
the problem turns out to be in chanaged InvertAll behaviour. It seems like mugen 1.1's interpretation of `invertall` is to also invert the alpha (so `add` becomes `sub` and other way around), while in winmugen/mugen 1.0/ikemen go this is not the case. In this case compatibility mode that replicates this behaviour depending on character mugenversion may be needed.

**Comment by JeanneSoul** [comment]
Ahh i see... for the sake of engine behavior, in my opinion, mugen 1.1 for palfx behavior its better than 1.0 .. outside of those there is so many chars who implemented palfx from mugen 1.1 behavior but back to developer ,, if ikemen dev prefer for 1.0 behavior so be it.. in this case maybe make coders recode their chars who implemented palfx from 1.1 to ikemen GO and adapt to it..

**Comment by dbaldan** [comment]
> "mugen 1.1 for palfx behavior its better than 1.0"

I have to disagree with this. The way _invertall_ works in 1.1 is broken, because it should affect only the colors, not the alpha.
If you see the documentation, you will find there is no mention to alpha
http://www.elecbyte.com/mugendocs/sctrls.html#palfx

So Ikemen is acting right on this one.

**Comment by DakBulletStorm** [comment]
is there a way to work around this? im using the same char in one of my projects and im trying to figure out a way to change the palfx

**Comment by potsmugen** [comment]
> > "mugen 1.1 for palfx behavior its better than 1.0"
> 
> I have to disagree with this. The way _invertall_ works in 1.1 is broken, because it should affect only the colors, not the alpha. If you see the documentation, you will find there is no mention to alpha http://www.elecbyte.com/mugendocs/sctrls.html#palfx
> 
> So Ikemen is acting right on this one.

This thread is old but since this issue has become relevant again I just wanted to say that this is also how I feel. If invertblend is to be a separate parameter, then I think invertall should just do what it says it does. For Ikemen/future characters I mean. For Mugen characters it could default to however that specific Mugen version worked.
