### ISSUE TITLE
Implement "Done.anim" on the VS screen.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#316]
https://user-images.githubusercontent.com/77592586/127728441-68b7e7ac-6062-4ced-8424-7e21b02e9f52.mp4

"pX.face.done.anim =" parameter is only working with the last character selected.

**Comment by Windblade-GR01** [comment]
Also there is another problem.
The `done` animation on the select screen does not display at all.

**Comment by K4thos** [comment]
> Also there is another problem.
> The done.anim/done.spr on the VS screen does not display at all.

this is not a problem, works as intended. It should not be changed unless proper kof style order selection is implemented (where dedicated buttons confirm characters) - something I'm considering but definitely not for 0.98.

As for the reported problem, can't reproduce it so I assume it has been already fixed since the version Pedro is using:

https://user-images.githubusercontent.com/8928195/127735408-5a160777-af6f-44af-a136-d3f739627d41.mp4

**Comment by K4thos** [comment]
I've menaged to reproduced it with `p1.face.num` set to 1. So yeah, there is a bug here in select screen.

**Comment by UrsoManso** [comment]
>since if you have only 1 portrait displayed, but still remaining characters for selection, there is no time to display additional animation - you have control over next character selection right away, so that character portrait should be visible on screen.
I actually thought about it, that's why I asked first here: https://discord.com/channels/233345562261323776/282927929548210177/870868680035155988
Instead of straight up reporting as a bug, but Gacel told me that it shouldn't be happening so...
>Is there any commercial game that works like your screenpack that could be used as a reference for how it should work?
No idea honestly.

**Comment by K4thos** [comment]
> Is there any particular reason why done.anim and **select.snd** only trigger on the last character picked?

select.snd should play for each character, so this part indeed can be considered a bug

**Comment by K4thos** [comment]
to not create confusion I've removed unused done.anim parameters from system.base.def . Order confirmation animation will be likely implemented one way or another in future, once we decide how versus screen should work - I'm considering optionally implementing something closer to KoF order confirmation with buttons in future due to popular demand.

**Comment by K4thos** [comment]
finished working on kof style order selection: https://github.com/K4thos/Ikemen_GO/commit/9c9531bff9a22e105e68b554c3ee88537f02c831
Which means the enhancement request has been fulfilled, ticket can be closed
