### ISSUE TITLE
external shader support

### ISSUE THREAD

**Issue by shanbady** [ikemen-engine/Ikemen-GO#323]
I've been trying to add external shaders (by dropping them into exernal/shaders) but for some reason no external shader I have tried thus far work. They either cause the app to crash (with no useful error output) or cause the screen to go black. Can someone point me to other external shaders that work in Ikemen besides the built-in ones?

**Comment by slzero-X** [comment]
You likely have to make them yourself, or modify the code to how Ikemen GO formats them. It might sound complicated, but with enough practice, is not really that hard.
Look at the built-in ones that Ikemen GO has, such as scanline.vert or scanline.frag. Take a look at those two and figure out how they work. Eventually you'll understand it and port the ones that the community made for MUGEN 1.1 to Ikemen GO by changing some of the code.
If we want to replicate exactly how Elecbyte in MUGEN 1.1 implemented it, it be an daunting task alone since the official engines are not open source.

**Comment by UrsoManso** [comment]
Reshade works just fine with Ikemen.
