### ISSUE TITLE
Command triggering the wrong special

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#350]
https://user-images.githubusercontent.com/77592586/132120237-8f745570-53be-40fa-ba9b-93e1e0416b5a.mp4
This is the move that is supposed to come out - MUGEN 1.1

https://user-images.githubusercontent.com/77592586/132120275-0ec0e858-2a08-4e10-84bd-952ef1e56d56.mp4
This is what comes out on IKEMEN when performing the same command

The special's command in question is DP+X/Y

[Rock.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7111220/Rock.zip)

**Comment by potsmugen** [comment]
This character uses a system where if you do an input the wrong way, the move won't come out. In this case this is the proper input:

```
[Command]
name = "弱ライジングタックル"
command = ~F, D, DF, a
time = 15
```

And this is the wrong one:

```
[Command]
name = "ライジングタックルミス"
command = ~F, D, DF, $D, a
time = 15
```

From what I recall from other issues I encountered while experimenting with shortcuts (seen in #463), Ikemen's input parser can read more than one directional input in the same frame. So since doing DF technically respects the "DF, $D" sequence in the second input, the wrong command is recognized and the move doesn't come out.

Mugen's input parser can only read one direction per frame in a given command so this conflic doesn't exist. This is how Ikemen's should work as well.
