### ISSUE TITLE
Seravy's Characters will hint a Memory lag

### ISSUE THREAD

**Issue by cyliamargatroid** [ikemen-engine/Ikemen-GO#366]
If you're not using DDR4 8GB RAM, According to Ikutron, When you play as Seravy's Reimu, That uses a Spell Cards that surround it with rays and if it damages it adds a lag of 3 seconds or a little more.
This causes a lot of lag or possible shutdowns or crash.

It somehow doesn't happen on MUGEN 1.0

**Comment by K4thos** [comment]
Can't reproduce the problem or observe any unusual memory spikes. But your "Spell Cards that surround it with rays" description is way to vague to be sure. Please update the description following bug report template (providing repro steps, video, or at least input commands for the move), otherwise the ticket will be closed.

**Comment by IkuTronHD** [comment]
The move name is Spell (2) Barrier of 4 Gods
