### ISSUE TITLE
power bar reset after getting hit

### ISSUE THREAD

**Issue by Adnan1091** [ikemen-engine/Ikemen-GO#373]
http://www.mediafire.com/file/d68gaddxb1c0pvn/____M206+SAGAT+beta+5.3.rar/file this char's power bar gets deleted after getting hit.Works fine on mugen 1.1

**Comment by K4thos** [comment]
it's cased by ikemen go negative states appending feature. These 2 files loaded from within DEF have duplicated [statedef -2] declaration:
`st6=Coding/sf4focusattack.cns
st7=Coding/sfVfocusattack.cns`

No need to change anything since for 0.98.2 we're implementing ikemenversion functionality explained here: https://github.com/K4thos/Ikemen_GO/wiki/wip
this compatibility problem is already solved internally
