### ISSUE TITLE
impossible to work, 5 GbRAM consumed

### ISSUE THREAD

**Issue by shurato** [ikemen-engine/Ikemen-GO#389]
please prioritize the memory issue ahead of any bugs as it is getting impossible to work consuming 5 gigs of ram.

![image](https://user-images.githubusercontent.com/7958164/141660011-b07b6acc-3025-4e22-aa58-ee8351b2f72c.png)

**Comment by Orochikyocr** [comment]
You can clone your system and fight sff and convert the copy to  SFFV1 aka indexed sprites.
This is only happening with 24bit sprites SFFV2.

**Comment by shurato** [comment]
do you mean pass to mugen 1.1?

![image](https://user-images.githubusercontent.com/7958164/141826480-9d1a9782-c0d7-4edd-986a-6769da1aa998.png)

**Comment by Orochikyocr** [comment]
Select Mugen 1.0 and let the fighter factory index all the sprites.
It will take some time according to your CPU speed. 
That is letting me work on some tag and training code for a game
I won't lie to you, maybe the results will look like shit, but it is a workaround that allows you to keep working on the project while the bug is fixed.
The other alternative is to use the default fight.def. In my case, the fight.def was consuming up to 2 gb alone. I wasn't able to use ctrl + F4 to test changes on the code because the pc was freezing.

**Comment by Windblade-GR01** [comment]
This is a know bug. (See: #265)
I still not managed to get it fixed.

**Comment by K4thos** [comment]
not solved yet, the ticket is closed for maintenance reasons - duplicate report
