### ISSUE TITLE
Knockdown sound issues on tag mode.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#403]
First of all I want to you pay attention to how the sound properly works, this in single mode.

https://user-images.githubusercontent.com/77592586/145505401-5935999a-9df6-436c-9116-c89d40a8cc28.mp4

Next is tag mode, where the issues happens.

https://user-images.githubusercontent.com/77592586/145505488-dd453910-ed68-46ca-bde6-3407d178a755.mp4

As you can see, not only the knockdown sound is louder, but if first character dies, the sound effect disappears from the rest of the team. Now here's something worth mentioning:

https://user-images.githubusercontent.com/77592586/145505648-6768bce3-e65f-441f-a40f-d7d740633094.mp4

If the first character remains alive while another dies, he still plays the sound, but the other ones won't.

[Kyo.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7689633/Kyo.zip)
Move is: bdb+light kick.

Same issue also happens in some moves from other characters.

**Comment by K4thos** [comment]
as far as I can tell this is all caused by incorrect use of triggers/redirections and is not an engine problem. Character has been coded with single mode in mind, not larger team sizes.

I assume the sound that triggers upon ko is played by your whole team instead of a single character, triggered at the same time, playing the same sound, which results in increased volume.
```
[State -2, 音を鳴らす]
type = PlaySnd
triggerall =!var(31)
triggerall = P2Movetype = H
trigger1 = p2stateno = 5611 && enemy,time = 1
trigger2 = p2stateno = 5614 && enemy,time = 1
trigger3 = p2stateno = 5616 && enemy,time = 1
value = s6,1
Persistent = 0
```

Try adding following line to limit execution just to 1 character (untested)
```ini
triggerall = playerNo = teamLeader
```

Second problem is most likely caused by incorrect use of redirections (written assuming that there is only 1 enemy = player 2)

**Comment by UrsoManso** [comment]
This line fixes the issue which the sound effect stop playing for the other characters if the first one dies, but it is still loud. That's good enough I guess.

**Comment by K4thos** [comment]
try this:
```ini
[State -2, 音を鳴らす]
type = PlaySnd
triggerall =!var(31)
triggerall = target,movetype = H
trigger1 = target,stateno = 5611 && target,time = 1
trigger2 = target,stateno = 5614 && target,time = 1
trigger3 = target,stateno = 5616 && target,time = 1
value = s6,1
Persistent = 0```
in this case code will run only if your target (the guy who you're actually hitting) is meeting criteria, not just first enemy.

`triggerall = playerNo = teamLeader` would make more sense for the knockout sound that is running at end of round from negative states, which also seems louder in tag (so is executed by more than 1 player at the same time). From what I see in Kyo files this character was created exclusively with single team mode in mind, so changes like these may be needed elsewhere. Simul was not very popular in mugen, so some author didn't bother to write code that works reliably with larger team sizes.

**Comment by UrsoManso** [comment]
It is still happening, but I don't think its related to other characters.

https://user-images.githubusercontent.com/77592586/147043265-650b99fc-e96d-4fc5-aa5d-61230382e501.mp4

As you can see here, in tag mode the ground effect triggers twice, so that's probably the what's happening with the sound effect as well.

**Comment by K4thos** [comment]
I guess you will have to modify triggers in similar fashion for the code responsible for ground bounce than. Or recoding it completely to use character's normal states instead of negative states for stuff like this (I don't think using negative states for ground bounce makes sense in the first place, unless I'm missing something).

Either way, as far as I can tell, this is not an engine bug or compatibility problem since I was able to confirm this char code running at the same time by more than 1 team member and triggers affecting wrong enemies in mugen 1.1 simul mode.

**Comment by K4thos** [comment]
> This line fixes the issue which the sound effect stop playing for the other characters if the first one dies, but it is still loud. That's good enough I guess.

tested on latest github build and I can't hear a difference in sound volume compared to mugen with the same volume settings. Adding `triggerall = playerNo = teamLeader` (which fixes buggy code of this character that executes the same sound, at the same frame, on multiple channels) makes the volume the same as in single mode for me. I don't see anything to fix here, so I'm removing bug label.

**Comment by K4thos** [comment]
As mentioned the reason why it happens is buggy character code (not created with simul/tag modes in mind), nothing to fix on the engine side. With sound normalizer fixed the problem will be less apparent volume wise, if audio ducking is enabled in options (of course the character still needs changes to not run the same sound multiple times from negative states to work as intended and not increase volume at all)

**Comment by K4thos** [comment]
this change to audio normalize has been reverted for now, I will get to fixing it later
