### ISSUE TITLE
ForceFeedBack Sctrl not implmented yet

### ISSUE THREAD

**Issue by Amidweiz** [ikemen-engine/Ikemen-GO#409]
I'm not sure if this has been brought up before but the `ForceFeedBack` state controller is not implemented in Ikemen GO and it just returns back an error if called. Blossomko by The_None has such sctrl in it

https://www.justnopoint.com/lbends/index.php?location=chars

**Comment by K4thos** [comment]
This is not a bug.

Even though Ikemen doesn't support ForceFeedback yet (we're waiting for glfw library to finalise haptic feedback implementation), what crashes the compiler is buggy character code. As per documentation the accepted value for ForceFeedback waveform is `wave_type (string)` not `"wave_type" (string)`.

So even once sctrl is implemented this character will still print error due to wrong syntax (same way mugen prints error when you try to enclose Explod `postype = postype_string (string)` argument with quotes etc.)

The reason why mugen doesn't complain about it is because compiling ForceFeedback is disabled since dosmugen. We could disable it too for the time being, but I don't see a point when the exact same error will show up once sctrl is fully supported (which hopefully won't be long from now since glfw status for it is "urgent" and there is pull request with it ready)

**Comment by slzero-X** [comment]
According to Choon, ForceFeedback has the same bytecode as Null. So in turn basically means its useless, as it doesn't serve any practical purpose.
Though since IKEMEN Go is designed to bring MUGEN's unused features back to light, ForceFeedback will eventually make a comeback as well, though as of now it is not implemented yet.
All you really have to do with Blossomko is just remove those ForceFeedback sctrls and she should work just fine.

**Comment by K4thos** [comment]
in next build both wave_type and "wave_type" syntax will be supported, for backward compatibility sake
