### ISSUE TITLE
When I play in Tag mode, lifebar disappears

### ISSUE THREAD

**Issue by VELKA6421** [ikemen-engine/Ikemen-GO#469]
https://user-images.githubusercontent.com/102023851/159647498-728ccbcf-3446-4502-a426-0b10fcaa0c63.mp4

#===============================================================================
# StateTagWaitingOutside
#===============================================================================
[StateDef 5611;
	type: A; moveType: I; physics: N;
	anim: const(AnimStanding);
	velSet: 0, 0; ctrl: 0;
]
assertSpecial{flag: invisible; flag2: noAutoTurn}
screenBound{value: 0; moveCamera: 0, 0}

# force standby character to always stay outside visible area
posSet{
	x: (playerId(getPlayerId(teamLeader)),pos x
		- playerId(getPlayerId(teamLeader)),screenPos x - const240p(160)) * -facing;
	y: playerId(getPlayerId(teamLeader)),pos y
		- playerId(getPlayerId(teamLeader)),screenPos y - const240p(160);
}

I think, it's wrong StateDef 5611 how can i fix that? Ikemen version is 0.98.1

**Comment by K4thos** [comment]
first of all we only support the most recent version of the engine (0.98.2 as of today), so consider updating.

As for the question - if lifebar disappears than the reason for it is character using AssertSpecial sctrl with nobardisplay flag. Look for it in character, analyze trigger conditions and make appropriate changes if needed. There is nothing we can do on engine side since that code is directly in character states. You can't alter that behavior from within tag.zss (which snippets you've posted above).

**Comment by VELKA6421** [comment]
> 

https://user-images.githubusercontent.com/102023851/159674984-ff03cd5d-05d6-423d-8d29-e78aca561129.mp4

Considering that the same problem occurs in version 0.98.2, I think it may be a character problem. anyway thanks for comment i check my chars

**Comment by Blac-Dragoon** [comment]
Does your code look like this?

`[State -2, Intro]
type = AssertSpecial
triggerall = !RoundsExisted
trigger1 = roundstate = 0
trigger2 = roundstate = 1
flag = NoBarDisplay`

**Comment by GAMER981** [comment]
[State 0, AssertSpecial]
type = AssertSpecial
trigger1 = 1
flag = noBG           what code to write?
flag2 = noFG           what code to write?

What is the solution for noBG,noFG, multiple files like this in three cns. files in the char, tag works ok but lifebars not showing, only visible when char makes a special,supercancel ??
THNX !
