### ISSUE TITLE
Q doesn't take throw damage

### ISSUE THREAD

**Issue by Adnan1091** [ikemen-engine/Ikemen-GO#515]
Q by umihei doesn't take throw damage from chars like sf3 ryu and ibuki.

**Comment by EgyLynx** [comment]
Hnnghh? Are these Ruy and duki take throw damage each orther?

**Comment by NeatUnsou** [comment]
Well, it wasn't a bug in IKEMEN, the same thing happens in MUGEN.
While GM's SF3 character has P2StateNo = 5100 as a condition for TargetLifeadd, Umihei's SF3 character does not take any damage because it shifts to 5109 when down.
Replacing all P2StateNo = 5100 with P2StateNo = [5100,5109] in _N2.cns will solve this problem.
