### ISSUE TITLE
Some problems with the included Dizzy system

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#561]
These aren't so much problems with the engine itself as they are with Dizzy.zss, but:

1 - The Dizzy state (default 5300) needs a HitFallReset. If the move that stuns the opponent is a knockdown, the first hit after he's dizzy will also knock down.

2 - If you change the Default.LifeToDizzyPointsMul constant to anything but 0, redizzy combos become possible. That is, hitting an opponent that is already dizzy will still do stun damage.

3 - If you juggle the opponent just as he's stunned, he will skip the dizzy state when he lands.

4 - The dizzy state should be vulnerable to throws, somehow. Most chars miss since it's Movetype=H.

5 - If you hit the opponent while his dizzy points are regenerating, your attack will do slightly less stun damage than it's supposed to, since the points still regenerate for 1 frame when he's hit.

6 - TargetLifeAdd is currently unaffected by Default.LifeToDizzyPointsMul. Also this is more of a feature request, but there could be a parameter so you could make this Sctrl add dizzy points or not. Either a flag like "Kill", or a multiplier that defaults to said constant.

7 - Not a bug, but in most games the opponent is invulnerable immediately once DizzyPoints = 0 and until he get ups. I think this should be the default Ikemen behaviour.

8 - Another feature request that I should post on its own but I might as well leave it here: there could be an AssertSpecial flag to disable Dizzy Points damage (as well as Guard Points for that matter). As in, once asserted, none of your attacks deal stun damage to the opponent.

I think that's it.

**Comment by K4thos** [comment]
1. I'm not sure how to do it from within cns/zss code
2. Fixed. HitDef now skips dizzy points applying, if target is already dizzy
4. I've simply changed statdef 5300 moveType from  U to I. Not sure if it can have negative consequences?
6. Added targetLifeAdd sctrl dizzy parameter: 1 enables dmg to dizzy points conversion support using Default.LifeToDizzyPointsMul const (1 by default).
7. Godd idea. Added both requested AssertSpecial flags. And with this change I was able to assign Default.LifeToDizzyPointsMul in common.const instead of relying on receivedDamage trigger (nodizzypoints is now asserted in dizzy.zss when hitDefAttr = SCA, HA, so workaround to achieve it is not needed)

1, 3, 5, 8 - I think this stuff can be handled by editing dizzy.zss file but I'm afraid I don't have enough experience with character creation to implement such changes without introducing regressions. Any help with it would be appreciated. Feel free to edit dizzy.zss, if you like, all of the proposed changes would be internalized.

**Comment by potsmugen** [comment]
1 - My bad. I meant a HitFallSet with value = 0

2 - The important thing here is also that this behaviour is only reset once the dizzy victim can act again. I forgot to specify that

4 - That works but the combo counter will then reset while the character is dizzy. Unless you apply the Dizzy flag sooner, which is what I did below

6 and 8 - Excellent

1, 3, 5, 7 - I'm not quite used to the ZSS language but I gave it a shot. Every change should be commented.
[dizzy.zip](https://github.com/ikemen-engine/Ikemen-GO/files/8886278/dizzy.zip)

**Comment by K4thos** [comment]
Thanks! Implemented your changes to latest version of zss file, renamed flags, fixed the combo counter. Please let me know if you still find some oddities with it.

**Comment by K4thos** [comment]
- added notHitBy to dizzy states
- new constant: Super.LifeToDizzyPointsMul (works like Default.LifeToDizzyPointsMul, but for super moves)

With this constant calling assertSpecial flag is not needed and moves with actual dizzypoints values assigned in HitDef will do intended dizzy damage.
