### ISSUE TITLE
Loss of frame rate with debug mode

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#573]
I've read that this would be fixed after 0.98.2, but it's still happening to me after compiling the latest versions, so I guess it's worth mentioning.

Whenever I activate the debug mode, I get a significant loss of frame rate, as shown here:

https://user-images.githubusercontent.com/107247004/174491906-3154612a-5068-4f83-98f5-498a3a404ae5.mp4

As a developer this is currently the most bothersome issue with the engine.

**Comment by Windblade-GR01** [comment]
Seems the problem is caused by the debug console log.
POTS if you set `DebugConsoleRows` in `config.json` to 0 does the slowdown dissapear?

**Comment by GaryCXJk** [comment]
I have a similar issue where there's a lot of frame rate drop on the character select screen, though in my case, it's only on the character select screen, nowhere else. On the release build, there's no such lag. I can also confirm that it's purely the binary, as I've copied over the externals folder to the release build folder, and there's no issues.

My personal hypothesis is that there's some optimization going on when cross-compiling, as the release build has builds for all operating systems. I'm going to try and get docker working, but it also seems that the image is outdated, as that uses Golang 15.0 instead of the now required 18.0.

**Comment by potsmugen** [comment]
Just to clarify, I have this issue with fonts both in 0.98.2 and the latest build.

**Comment by EgyLynx** [comment]
Lastest build is 0.98.2...

**Comment by potsmugen** [comment]
I just noticed a random thing that may or not be useful, in that I don't have this issue with Ikemen GO 0.98.0

**Comment by Lazin3ss** [comment]
The engine does a draw call (that means, 1 CGO call + 1 GPU call) for every glyph displayed here, and that's quite resource intensive. Only way to optimize this I can think of is to implement batching in the renderer. I'd like to implement that myself, but I still don't have enough knowledge on OpenGL to do that.

**Comment by potsmugen** [comment]
Fixed by assemblaj's changes to font rendering (ikemen-engine/glfont#004).
