### ISSUE TITLE
Methods to reduce the occupation of running memory

### ISSUE THREAD

**Issue by brokenstar054** [ikemen-engine/Ikemen-GO#587]
Hello, our team has made a game with Ikemen go, but its loading speed is very slow due to resource occupation, so we would like to ask if there is any optimization method. In other words, is there anything that can be modified in the engine. In order to make the problem description more specific, a game compression package has been attached.Because I can't speak English, I can only use machine translation.&nbsp;I'm sorry if it bothers you.
link：http://mail.qq.com/cgi-bin/ftnExs_download?k=7a6238365bd0dd19d2c1ec901338514a045500040108535c1a525b000515575d0456150f0759014802560005575a575755530b02352063246529767f72703736172471717d6c43d686abc518475911650a&t=exs_ftn_download&code=7b8658ce

**Comment by NeatUnsou** [comment]
I looked at the package and it seems to have a large number of images and a large size.
There is not much you can do: change the 32bit images to 8bit, reduce the number of images, crop the images.
Cropping images is especially important. png compresses the size of blank areas, reducing their size on disk, but with VRAM they are uncompressed and consume memory.
Since system.sff will always be in memory, it is worth the effort to reduce its size. The format of the AIR file can be changed not only in terms of coordinates and transparency, also scale and angle, so that the number of images can be reduced without degrading the expression.
