### ISSUE TITLE
Numbuh 3 and Kang AnimExist bug

### ISSUE THREAD

**Issue by jenngra505** [ikemen-engine/Ikemen-GO#963]
### Describe the bug

Numbuh 3's F.R.A.P.P.E special and Kang's projectile specials cause a ton of debug flood and traps the opponent in their current animation against opponents without a freeze animation.

### To Reproduce

1. Download Numbuh 3 from https://1drv.ms/u/s!AqN1Ini5-I2Ig9MLCMB6UbdIL2xUSQ?e=daoFwS or Kang from https://drive.google.com/drive/folders/1xYII5wpDZmAPwkuPzfXK2RyFjxlzixmu?usp=sharing
2. Use F.R.A.P.P.E by using QCB, Punch against Kung Fu Man or one of Kang's projectiles with QCF, Punch
3. See error

### Expected behavior

Kung Fu Man will go into animation 5015

### Screenshots / Video

![ikemen001](https://user-images.githubusercontent.com/18198665/215614129-6a0e8ccb-bd65-41b8-8800-4bbf0e5f7813.png)
![ikemen002](https://user-images.githubusercontent.com/18198665/215618403-dcf8f64d-b344-4d48-91c4-0cb6968869a2.png)

### Engine Version (or source code date)

1/30/2023

### Operating system

Windows

**Comment by K4thos** [comment]
This change fixes the problem but I'm not confident if it won't lead to a regression for other chars. Would appreciate review from @NeatUnsou or @Lazin3ss.

I think this code may also need changing:
```
		case OC_pow:
			v2 := sys.bcStack.Pop()
			be.pow(sys.bcStack.Top(), v2, sys.workingChar.ss.sb.playerNo)
```
to use c.ss.sb.playerNo instead, although not sure about it.

**Comment by potsmugen** [comment]
The fix used for these bugs is kind of more like a patch. It is tricking the engine instead of targeting the problem. That has side effects like making bytecode errors be printed from the wrong character. The fix is also only accurate half the time to begin with, depending on who does or doesn't have an animation with that number.

The way AnimExist works in Mugen is not as it is documented, as we've grown used to. It has nothing to do with the owner of the state. It checks if the animation exists in the current animation table the character is using. So, in the same state, it can return different things whether you used ChangeAnim or ChangeAnim2.

The Kang bug goes one step further. K4thos was right in that the character is just flat out buggy. But it made me discover that, in Mugen, when changing animation tables (ChangeAnim2) and the destination anim doesn't exist, the character will change into whatever animation is in the same index as in the previous table. Ikemen is more pragmatic and just doesn't change animations when things are invalid.

I'm doing some changes that will remove the patch, fix bytecode debugging and make the code more accurate. But I'm not adding the animation index thing. At least not yet.
